"""Export a trained checkpoint to ONNX and the fixed C++ firmware header."""

from __future__ import annotations

import argparse
from pathlib import Path

import torch

from .model import DepthResidualMLP


def _fmt(value: float) -> str:
    return f"{value:.9g}f"


def _array(values: list[float], indent: str = "    ") -> str:
    return "{ " + ", ".join(_fmt(value) for value in values) + " }"


def write_header(path: Path, checkpoint: dict, model: DepthResidualMLP) -> None:
    state = model.state_dict()
    w1 = state["net.0.weight"].detach().cpu().tolist()
    b1 = state["net.0.bias"].detach().cpu().tolist()
    w2 = state["net.2.weight"].detach().cpu().tolist()
    b2 = state["net.2.bias"].detach().cpu().tolist()
    w3 = state["net.4.weight"].detach().cpu().tolist()[0]
    b3 = state["net.4.bias"].detach().cpu().tolist()[0]
    input_mean = checkpoint["input_mean"]
    input_std = checkpoint["input_std"]
    window = int(checkpoint["window"])
    input_dim = len(input_mean)
    hidden1 = len(b1)
    hidden2 = len(b2)

    lines = [
        "// Generated by 5_DepthLearning/learning/export.py. Do not edit by hand.",
        "#ifndef SQUID_DEPTH_RESIDUAL_MODEL_WEIGHTS_H",
        "#define SQUID_DEPTH_RESIDUAL_MODEL_WEIGHTS_H",
        "namespace depth_residual_weights {",
        "constexpr bool kReady = true;",
        f"constexpr int kWindow = {window};",
        "constexpr int kFeaturesPerFrame = 5;",
        f"constexpr int kInputDim = {input_dim};",
        f"constexpr int kHidden1 = {hidden1};",
        f"constexpr int kHidden2 = {hidden2};",
        f"constexpr float kInputMean[kInputDim] = {_array(input_mean)};",
        f"constexpr float kInputStd[kInputDim] = {_array(input_std)};",
        f"constexpr float kOutputMean = {_fmt(float(checkpoint['output_mean']))};",
        f"constexpr float kOutputStd = {_fmt(float(checkpoint['output_std']))};",
        "constexpr float kW1[kHidden1][kInputDim] = {",
    ]
    lines.extend("    " + _array(row) + "," for row in w1)
    lines.extend([
        "};",
        f"constexpr float kB1[kHidden1] = {_array(b1)};",
        "constexpr float kW2[kHidden2][kHidden1] = {",
    ])
    lines.extend("    " + _array(row) + "," for row in w2)
    lines.extend([
        "};",
        f"constexpr float kB2[kHidden2] = {_array(b2)};",
        f"constexpr float kW3[kHidden2] = {_array(w3)};",
        f"constexpr float kB3 = {_fmt(b3)};",
        "}  // namespace depth_residual_weights",
        "#endif  // SQUID_DEPTH_RESIDUAL_MODEL_WEIGHTS_H",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True)
    parser.add_argument("--onnx-output", required=True)
    parser.add_argument("--cpp-output", required=True)
    args = parser.parse_args()

    checkpoint = torch.load(args.model, map_location="cpu")
    hidden_dims = tuple(checkpoint["hidden_dims"])
    model = DepthResidualMLP(len(checkpoint["input_mean"]), hidden_dims)
    model.load_state_dict(checkpoint["model_state"])
    model.eval()

    dummy = torch.zeros(1, len(checkpoint["input_mean"]), dtype=torch.float32)
    onnx_output = Path(args.onnx_output)
    onnx_output.parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        model,
        dummy,
        onnx_output,
        input_names=["features"],
        output_names=["depth_residual"],
        opset_version=13,
        dynamic_axes={"features": {0: "batch"}, "depth_residual": {0: "batch"}},
    )
    write_header(Path(args.cpp_output), checkpoint, model)
    print(f"saved {onnx_output}")
    print(f"saved {args.cpp_output}")


if __name__ == "__main__":
    main()
