# Generated by compile_finalize.py. Do not edit.
set(ESPDL_COMPILE_SRCS
    dl/base/dl_base_conv_loop.cpp
    dl/base/dl_base_dwconv_loop.cpp
    dl/base/dl_base_conv_select.cpp
    dl/base/isa/tie728/dl_tie728_s16_conv2d.S
    dl/base/isa/tie728/dl_tie728_s16_unaligned_conv2d.S
    dl/base/isa/tie728/dl_tie728_s8_conv2d.S
    dl/base/isa/tie728/dl_tie728_w8a16_conv2d.S
    dl/base/isa/tie728/dl_tie728_w8a16_unaligned_conv2d.S
    dl/base/isa/tie728/dl_tie728_s16_depthwise_conv2d_block.S
    dl/base/isa/tie728/dl_tie728_s8_depthwise_conv2d.S
    dl/base/isa/tie728/dl_tie728_s16_unaligned_depthwise_conv2d.S
    dl/base/dl_base_requantize_linear.cpp
    dl/base/isa/tie728/dl_tie728_s8_requantize_linear.S
    dl/base/isa/tie728/dl_tie728_s16_requantize_linear.S
)
