/* Generated by compile_finalize.py. Do not edit. */
#pragma once

#define DL_COMPILE_ALL 0

#define DL_OP_Gemm 1
#define DL_OP_RequantizeLinear 1

#define DL_KERNEL_DL_TIE728_S8_UNALIGNED_CONV2D_11CN 1
